/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppAlert: typeof import('./src/components/AppAlert.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    PostFilter: typeof import('./src/components/posts/PostFilter.vue')['default']
    PostForm: typeof import('./src/components/posts/PostForm.vue')['default']
    PostItem: typeof import('./src/components/posts/PostItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
